### ISSUE TITLE
Integrate notifications for toll roads and restricted access

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-text-instructions#121]
With OSRM 5.9 we will introduce a new property to the `RouteStep`:

- `classes` **Arrray** of **String** that contains information about user-defined classes (e.g. "toll", "restricted")

We also emit a new `notification` instruction when one or more class gets added, and there is no other instruction at that position (like a ` turn`).

- If we see that the `classes` property contains a `"toll"` value we want to include a warning in the instruction like "You are entering a toll road."
- If we see that the `classes` property contains a `"restricted"` value we want to include a warning in the instruction like "You are entering a road with restricted access."

**Comment by freenerd** [comment]
Not sure we'd actually want to emit a text instruction for this. Instead these might be sufficient as visual indicator in list views/during route planning?

@1ec5 what's your take?

**Comment by daniel-j-h** [comment]
Hm if we don't want to emit a text instruction here then why do we emit a `Notification` in the backend and not have it on the intersection array for classes along the route?

**Comment by 1ec5** [comment]
> Not sure we'd actually want to emit a text instruction for this. Instead these might be sufficient as visual indicator in list views/during route planning?

I guess the answer depends on the class in question. For `toll`, it makes the most sense for the user to be notified before starting the route (visually, at least). As long as some part of the route response indicates the use of a toll road, that’s good enough for the application.

One could make an argument for audibly alerting the driver when they’re nearing a toll plaza, but I think that would require something quite different than the `classes` property. The toll plaza may be located either at the beginning or the end of the road, so that would affect the timing significantly. It may even be an [electronic toll tag reader](https://en.wikipedia.org/wiki/Electronic_toll_collection) that doesn’t even require the driver to slow down.

I’m not entirely clear on the `restricted` class – does this class occur when `access=private` or `motor_vehicle=no` (in the car profile)?

As for the other classes implemented in Project-OSRM/osrm-backend#4204:

* For `ferry`, do we need to implement anything beyond our existing `ferry` maneuver type support?
* `motorway` is all about #51: we’ll want to suppress the road name. Ideally we’d have `trunk` as a class, too, so we can put the ref in front of the road name in instructions.
