### ISSUE TITLE
Remove ref from name when not a motorway

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-text-instructions#133]
With [this line](https://github.com/Project-OSRM/osrm-text-instructions/pull/129/files#diff-168726dbe96b3ce427e7fedce31bb0bcR151) we are still announcing the ref as part of the name in the case of a non-motorway. This is too verbose. Can we remove?

/cc @1ec5 @bsudekum

**Comment by 1ec5** [comment]
It’s important to include the route number for a non-motorway when it’s available. Many U.S. routes and state routes are non-motorways, but as the user approaches the route, they may see at least one [advance route turn assembly](https://mutcd.fhwa.dot.gov/htm/2003r1/part2/fig2d-06-1_longdesc.htm) long before they see the blade sign indicating the street name. We have no way of knowing whether a road is more identifiable by its route number or its name at a particular intersection; OpenStreetMap doesn’t make that distinction.

In the following example, the route numbers are prominently posted, while the street name is difficult to spot:

[![advance](https://user-images.githubusercontent.com/1231218/28655441-ddf9d0ce-7250-11e7-852e-28c2ce60f3aa.jpg)](https://www.mapillary.com/map/im/s91Li6MlnFFE7i_fql2TZQ)

[![blade](https://user-images.githubusercontent.com/1231218/28655473-16ff8c42-7251-11e7-8b31-c4402c01915c.jpg)](https://www.mapillary.com/map/im/Ui7ekFp2uxY-QWOK_rzfjg)

But if you approach the same street at an unsignalized intersection, the street name may be the only thing signposted, so we shouldn’t get rid of the name either:

[![pike](https://user-images.githubusercontent.com/1231218/28655582-a6a6c338-7251-11e7-9018-1077cf069e9c.jpg)](https://www.mapillary.com/map/im/-CEze39W6XHn5lEns7KaMQ)

**Comment by willwhite** [comment]
> It’s important to include the route number for a non-motorway when it’s available.

Other routing providers are announcing one or the other - not both - including in the situation you reference above.

Keep in mind that OSRM will continue to include route number data where available, so that it can be incorporated into turn banners. This is just about what is actually announced to the driver.

> We have no way of knowing whether a road is more identifiable by its route number or its name at a particular intersection; OpenStreetMap doesn’t make that distinction.

How do we determine this information? Do we need a mapping effort around this?

**Comment by 1ec5** [comment]
Agreed that it would be nice to announce only one, but the error rate would be too high as things stand. (Other routing providers aren't nearly perfect this regard either – it's a hard problem because signage isn't consistent.)

>> We have no way of knowing whether a road is more identifiable by its route number or its name at a particular intersection; OpenStreetMap doesn’t make that distinction.

> How do we determine this information? Do we need a mapping effort around this?

Among established tagging conventions in OSM, the closest thing I can think of is [destination sign relations](https://wiki.openstreetmap.org/wiki/Relation:destination_sign), which are primarily meant for "follow the route" instructions (Project-OSRM/osrm-backend#3542).

Any tagging scheme to distinguish between names useful and useless for wayfinding would have to rely on relations, because the data would differ from one intersection to the next and from one direction to another. But I suppose that would require Project-OSRM/osrm-backend#482.

**Comment by 1ec5** [comment]
Somewhat relatedly, I've noticed cases in which Google Maps announces both the destination (street name) and ref for an off ramp instruction, then omits the ref when repeating the instruction at the maneuver point. For example, in [this route](http://map.project-osrm.org/?z=18&center=32.837500%2C-97.108610&loc=32.837513%2C-97.110375&loc=32.836697%2C-97.099963&hl=en&alt=0), Google Maps says something like "take the exit to FM 157, Industrial Boulevard", followed by "take the Industrial Boulevard exit". (This Texas state highway is a freeway but doesn't use exit numbers.) I figure this is because "eff em one-fifty-seven" would make the instruction too verbose; at the same time, it is necessary to say at some point for wayfinding purposes. mapbox/mapbox-navigation-ios#331 would accomplish a similar effect on the client side, potentially requiring changes to this library.

**Comment by 1ec5** [comment]
The decision whether to identify a surface street by its route number requires additional context that is out of scope for OSRM Text Instructions at this time, given that this library needs to maintain compatibility with plain-vanilla OSRM instances. However, a more specialized client library might be better positioned to account for factors such as municipal boundaries.
