### ISSUE TITLE
Modifier in roundabout turns in can be confusing

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-text-instructions#140]
In https://github.com/mapbox/mapbox-navigation-android/issues/184 a user got confused by roundabout turns where we announce something like "at the roundabout turn left".

The idea behind this is the user should leave the roundabout to the left. But the "turn left" can be seen as confusing because you turn right to enter the roundabout in a right-hand sided driving country.

We should probably announce roundabout turns differently maybe "leave the roundabout to the right" or similar (not a native speaker, sorry).

https://github.com/Project-OSRM/osrm-text-instructions/blob/7485f8527cbe2820fbd2540d9959f1133ff7e3b4/languages/translations/en.json#L368-L389

Note: when we introduce a roundabout exit instruction in osrm (https://github.com/Project-OSRM/osrm-backend/pull/4358) we should double check that roundabout turns are atomic and do not come with an extra turn instruction to leave the roundabout.

cc @miccolis

**Comment by hdaymon** [comment]
I believe that this is handled in https://github.com/mapbox/directions-voice-instructions/issues/18

**Comment by MoKob** [comment]
@hdaymon the exit rotary part is unrelated to roundabout turns. A rotary is a large roundabout with a dedicated name (or traffic circle, not following roundabout rules).
A roundabout turn is a tiny traffic circle that does feel more like an intersection.

A possible solution here could be to use `Leave the roundabout to the left` instead of `At the roundabout turn right`. With this reformulation, I would assume that the confusion @daniel-j-h mentions here cannot happen.

**Comment by 1ec5** [comment]
How about leaving out any mention that there’s a roundabout? It’s just secondary information, akin to “at the large intersection”.
