### ISSUE TITLE
"Stay on" when continuing on the same road

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions#41]
Along the same lines as #30, it would be nice if we could say "Keep left to stay on Main St" if Main St. is the street both before and after the fork in the road.

/cc @freenerd @bsudekum @mayagao

**Comment by willwhite** [comment]
Isn't this the purpose of the `continue` maneuver type? If not, what is the continue maneuver type for?

The [OSRM docs](http://project-osrm.org/docs/v5.9.1/api/#stepmaneuver-object) say:

```
continue | Turn in direction of modifier to stay on the same road
```

**Comment by willwhite** [comment]
I'm perplexed by the continue maneuver. Based on what the docs say about "staying on the same road", I'd expect both of these to be `continue` because they both involve staying on the same road:

- [Continue left onto South Airport Boulevard](https://www.mapbox.com/get-directions/#17.25/37.64927/-122.40584?coordinates=-122.405445,37.6491;-122.406205,37.65003)
  - Confusing because this feels like a left turn
  - Ideal instruction would be "Turn left to stay on South Airport Boulevard"
- [Keep right at the fork onto I 395](https://www.mapbox.com/get-directions/#16.15/38.8772/-77.03817?coordinates=-77.03816520252614,38.87720262625558;-77.035699,38.878912)
  - Confusing because this is staying on the same road (I'm already on I 395
  - Ideal instruction would be "Keep right at the fork onto I 395"

Does `continue` make sense as a maneuver type or is it a flag that belongs on all other maneuver types to indicate when a road is staying the same?

/cc @MoKob

**Comment by willwhite** [comment]
[Here's another example](https://www.mapbox.com/get-directions/#16.36/37.48093/-122.1845?coordinates=-122.183232,37.481767;-122.184475,37.480919):

- We get a "Continue right onto Marsh Road"
- Then we get a "Turn left onto Marsh Road"

Why is the first one a `continue` and second a `turn`?

**Comment by willwhite** [comment]
> Why is the first one a continue and second a turn?

This is a bug that should be fixed in https://github.com/Project-OSRM/osrm-backend/pull/4400, but is not yet deployed.

Per voice with @daniel-j-h, the next action is to adjust the phrasing in our [`continue` instructions](https://github.com/Project-OSRM/osrm-text-instructions/blob/bdf31a49565e76db76a338f05913087c2d99b9db/languages/translations/en.json#L79-L105) to be more smooth. For example, instead of `Continue slightly right onto {way_name}` it should be `Turn slightly right to stay on {way_name}`.

This is immediately actionable and we should do this now.

However, I don't see how this will address the original `fork` case described in the OP. `fork` and `continue` are both maneuver types, but you can have a `fork` that continues. How we do handle that case? This leads me back to my original question:

> Does continue make sense as a maneuver type or is it a flag that belongs on all other maneuver types to indicate when a road is staying the same?

This would allow any instruction to be rephrased with "stay on" instead of "onto" which is confusing when you're already on the road in question.

**Comment by willwhite** [comment]
Here's an example of a `fork` instruction where the name is staying the same:

https://www.mapbox.com/get-directions/#16/36.9879/-122.0236?coordinates=-122.022312,36.989434;-122.02360473016304,36.987874443471256

Since this isn't a `continue`, I'm not sure we have enough information to make this instruction read "Keep right at the fork **to stay on** CA 1".

**Comment by willwhite** [comment]
Next action is to improve whatever we can by rephrasing `continue` instructions to use "stay on" language.

Unless, I'm missing something we might need some fixes upstream in OSRM in order to support `fork` instructions that `continue` on the same road.

**Comment by mcwhittemore** [comment]
@willwhite are these the instructions you are saying need to be changed?

https://github.com/Project-OSRM/osrm-text-instructions/blob/master/languages/translations/en.json#L82

https://github.com/Project-OSRM/osrm-text-instructions/blob/master/languages/translations/en.json#L87

**Comment by lyzidiamond** [comment]
@willwhite in making this change I noticed a couple test failures worthy of additional consideration:

-

**Comment by willwhite** [comment]
https://github.com/Project-OSRM/osrm-text-instructions/pull/142 is a big improvement but the instructions will still be bad for some of the example routes.

- [Will be "Continue left to stay on South Airport Boulevard" but should be "Turn left to stay on South Airport Boulevard"](https://www.mapbox.com/get-directions/#17.25/37.6491/-122.40544?coordinates=-122.405445,37.6491;-122.406205,37.65003)
- [Will be "Continue right to stay on Marsh Road" and "Continue left to stay on Marsh Road" but should be "Turn right to stay on Marsh Road" and "Turn left to stay on Marsh Road"](https://www.mapbox.com/get-directions/#16.36/37.48177/-122.18323?coordinates=-122.183232,37.481767;-122.184475,37.480919)

Thoughts on changing the "Continue" to "Turn" ?
