### ISSUE TITLE
Swift port

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-text-instructions#53]
Documenting that a swift port will happen:
- [ ] Transform instruction files to `.plist`
- [ ] Execute integration test suite
- [ ] Build and package

/cc @1ec5 @bsudekum

**Comment by 1ec5** [comment]
To be clear, this would consist of a script that could convert the JSON file to a plist on demand, plus whatever minimal Swift code we need to match the functionality currently in index.js.

**Comment by freenerd** [comment]
I'm not too-well-versed with the Apple ecosystem, but should this maybe be Objective C instead of Swift to reach full compatibility with all apps (new and old)?

**Comment by 1ec5** [comment]
Swift can bridge to Objective-C to some extent. But you're right, we might want to use Objective-C for the benefit of applications that need static linking. We'd end up using the same Foundation APIs either way.

**Comment by 1ec5** [comment]
Here’s how I’d prefer the Swift support to be structured:

* osrm-text-instructions implements an Instruction struct that holds all the data relevant to an instruction about a step. It would look similar to MapboxDirections.swift’s RouteStep class, minus all the Objective-C compatibility gunk.
* osrm-text-instructions implements an InstructionFormatter subclass of Formatter that takes an Instruction instance and outputs a localized string formatted for display or voice.
* MapboxDirections.swift implements a RouteStepFormatter subclass of Formatter that internally converts a RouteStep into an Instructions instance in order to then convert it into a user-friendly instruction string.

MapboxDirections.swift will depend on osrm-text-instructions, not the other way around. This way, MapboxDirections.swift can remain focused on the Mapbox Directions API without making compromises for direct OSRM-frontend usage. Meanwhile, osrm-text-instructions is shielded from the Objective-C API compatibility concerns that currently make MapboxDirections.swift a pain to develop. (Since osrm-text-instructions is such a new library, I don’t think there’s any demand for Objective-C compatibility for it. But if the demand arises, we can always write an ObjC compatibility layer in Swift.)

**Comment by 1ec5** [comment]
[OSRM Text Instructions for Swift](https://github.com/Project-OSRM/osrm-text-instructions.swift/) is functional and available.
