### ISSUE TITLE
Instructions containing pedestrian tokens

### ISSUE THREAD

**Issue by ronhippler** [Project-OSRM/osrm-text-instructions#62]
using the foot profile many names of steps are tokens like: ` {highway:pedestrian}`, `{highway:service}` or `{highway:footway}`

the compiled instructions are containing these tokens:
`Turn right onto {highway:footway}`

**Comment by daniel-j-h** [comment]
This is due to OSRM's default bike / walk fallback here:
- https://github.com/Project-OSRM/osrm-backend/blob/4ba8ccfcce50c1d1c6e91df34b85ecc98a116ec2/profiles/foot.lua#L157
- https://github.com/Project-OSRM/osrm-backend/blob/4ba8ccfcce50c1d1c6e91df34b85ecc98a116ec2/profiles/bicycle.lua#L221

Note: the car profiles does not do this as a fallback. If you're running your own OSRM server, feel free to adapt the profiles. Closing here as not actionable.

**Comment by daniel-j-h** [comment]
Opened a ticket for further discussion in osrm-backend: https://github.com/Project-OSRM/osrm-backend/issues/3231.

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/pull/3262 and will be in the next 5.5 release.
